# Generated by Django 5.1.3 on 2024-11-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatter', '0002_contact_session_key_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='formatted_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
