# Generated by Django 5.1.3 on 2024-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatter', '0003_alter_contact_formatted_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('instagram', 'Instagram')], max_length=20)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='vCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('company_info', models.TextField(blank=True, null=True)),
                ('social_links', models.ManyToManyField(blank=True, to='formatter.sociallink')),
            ],
        ),
    ]
